version: '3'

services:
  db:
    image: mysql:8.0
    container_name: payments-mysql
    user: root
    ports:
      - "3306:3306"
    volumes:
       - dbdata:/var/lib/mysql
    environment:
      - ACCEPT_EULA=Y
      - MYSQL_ROOT_PASSWORD=gitCheckout2022!
      - MYSQL_DATABASE=payments_api
      - MYSQL_USER=oscar
      - MSSQL_SA_PASSWORD=gitCheckout2022!
    restart: always
    networks:
      - payments-network

  webapi:
    image: "payments-api"
    container_name: payments-webapi
    ports:
      - "13401:13401"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:13401
    depends_on:
      - db
    networks:
      - payments-network
  
volumes:
  dbdata:
networks:
  payments-network: {}
