version: '3'

services:
  db:
    image: "payments-db"
    container_name: payments-mysql
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    expose: 
      - 3306
    volumes:
       - dbdata:/var/lib/mysql
    environment:
      - ACCEPT_EULA=Y
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=payments_api
      - MYSQL_USER=oscar
      - MSSQL_SA_PASSWORD=gitCheckout2022!
      - MYSQL_PASSWORD=gitCheckout2022!
    restart: always
    networks:
      - payments-network

  webapi:
    image: "payments-api"
    container_name: payments-webapi
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "13401:13401"
    environment:
      - ASPNETCORE_URLS=http://+:13401
    depends_on:
      - db
    networks:
      - payments-network
  
volumes:
  dbdata:
networks:
  payments-network: {}
